steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/trade-harmony-frontend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/trade-harmony-frontend:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/trade-harmony-frontend:${SHORT_SHA}'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/trade-harmony-frontend:latest'
    id: 'push-image-latest'

  # Step 3: Clone the Terraform infrastructure repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/HristevMartin/constructionPlatformInfra.git'
      - '/workspace/infra'
    id: 'clone-infra-repo'
    secretEnv: ['GITHUB_TOKEN']

  # Step 4: Update the Terraform variable with new image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/infra
        # Update the tfvars file with the new image
        sed -i "s|frontend_simple_image_name.*|frontend_simple_image_name = \"${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/trade-harmony-frontend:${SHORT_SHA}\"|g" environments/prod/terraform.tfvars
        
        # Show the change
        echo "Updated terraform.tfvars:"
        cat environments/prod/terraform.tfvars
    id: 'update-terraform-vars'

  # Step 5: Initialize Terraform
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd /workspace/infra/environments/prod
        terraform init
    id: 'terraform-init'

  # Step 6: Plan Terraform changes
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd /workspace/infra/environments/prod
        terraform plan -target=module.frontend_simple -out=tfplan
    id: 'terraform-plan'

  # Step 7: Apply Terraform changes (deploy to Cloud Run)
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd /workspace/infra/environments/prod
        terraform apply -auto-approve tfplan
    id: 'terraform-apply'

# Substitution variables
substitutions:
  _REGION: 'europe-west2'  # Change to your region
  _ARTIFACT_REPO: 'trade-harmony-images'  # Your Artifact Registry repo name

# Use Secret Manager for GitHub token
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/github-token/versions/latest
      env: 'GITHUB_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'